const googlefont =
{
  1: "Open Sans",
  2: "Roboto",
  3: "Lato",
  4: "Montserrat",
  5: "Poppins",
  6: "Oswald",
  7: "Alegreya",
  8: "Noto Sans",
  9: "Noto Serif",
  10: "Raleway",
  11: "Merriweather",
  12: "Source Sans Pro",
  13: "Work Sans",
  14: "Playfair Display",
  15: "Dancing Script",
  16: "Quicksand",
  17: "Cabin",
  18: "Ubuntu",
  19: "Fjalla One",
  20: "Arimo",
  21: "Anton",
  22: "Bitter",
  23: "Cousine",
  24: "Exo 2",
  25: "Karla",
  26: "Lora",
  27: "PT Sans",
  28: "Varela Round",
  29: "Zilla Slab",
  30: "Inconsolata",
  31: "Sacramento",
  32: "Noto Serif JP",
  33: "Noto Sans KR",
  34: "Lobster",
  35: "Muli",
  36: "Righteous",
  37: "Satisfy",
  38: "Archivo Narrow",
  39: "Crimson Pro",
  40: "Libre Baskerville",
  41: "Overpass",
  42: "Bungee Inline",
  43: "Spectral",
  44: "Sora",
  45: "Teko",
  46: "Julius Sans One",
  47: "Cedarville Cursive",
  48: "Fira Sans",
  49: "Hind Madurai",
  50: "Kanit",
  51: "Julius Sans One"
}

